### PR TITLE
API homework 1 completed

### PR DESCRIPTION
**Pull request by Dr-Java**

### CODE REVIEW

**Comment by DaniilPavlovEpam** [comment]
Hi Anastasia! 
Good job!  There are just few things to be fixed:
1) **CorrectWordSuggestionsTestCase** - please, utilize "Setup Script"/"TearDown Script" tabs for setting up precondition and postcondition for tests.
image

**IgnoreCaseOptionWithDataProviderTestCase** :
2) In current implementation there is one redundant step:
image

3) also there is another issue if one test case fails then next cases won't run. For example, I have changed one case to negative and got such result:
image
In order to avoid such situation open the test case's Options and change settings accordingly:
image
I expect to see such result: 
image

Best,
Daniil Pavlov

**Comment by Dr-Java** [comment]
Hi. Thank you for review. Mistakes were fixed.

**Comment by DaniilPavlovEpam** [comment]
Morning!  
№1 issue - fixed
№2 issued - not fixed
№3 issue - fixed 

In terms of №2 issue, try to 'Disable' second test step and run suite again.
image

Best, 
Daniil Pavlov

**Comment by DaniilPavlovEpam** [comment]
API HW 1 - Accepted

**Pull request merged**
